name: ğŸš€Deploy App...
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‰Get rep src code
        uses: actions/checkout@v3
      - name: âœ¨npm install
        run: npm ci
      - name: ğŸ› ï¸ Testing app...
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: ğŸ‰Get rep src code
        uses: actions/checkout@v3
      - name: âœ¨npm install
        run: npm ci
      - name: ğŸ› Lint tests app...
        run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‰Get rep src code
        uses: actions/checkout@v3
      - name: âœ¨ npm install
        run: npm ci
      - name: ğŸš€Build app...
        run: npm run build
