name: ğŸ› ï¸Test React App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‰Get rep src code
        uses: actions/checkout@v3
      - name: âœ¨npm install
        run: npm ci
      - name: ğŸ› ï¸run tests app
        run: npm run test
